context:
  version: "0.2.0"

package:
  name: spaday-ui5
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/1b/d9/ad71a1aa46dcede2830a5b103cf98a2b05abca60d3b0726b40e3d19273c9/spaday_ui5-${{ version }}.tar.gz
  sha256: 6b7c5f40daf9792ece7b8b7ecda36ec47fb6e0cc3b30eeec31074c69959dda9a

build:
  number: 0
  noarch: python
  script:
    env:
      SKIP_HATCH_JS: "1"
    content:
      - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
    - hatch-js
  run:
    - python >=${{ python_min }}
    - spaday >=0.8.2,<1

tests:
  - python:
      imports:
        - spaday_ui5
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: UI5 components and browser assets for spaday
  homepage: https://github.com/1kbgz/spaday-ui5
  repository: https://github.com/1kbgz/spaday-ui5

extra:
  recipe-maintainers:
    - timkpaine
